### ISSUE TITLE
[Feat] 서버 통신 관련 Extensions 개발 (2차)

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#13]
## 🛠 Issue
- 1차 작업에 이어서 서버와의 통신과 관련된 Extensions들을 개발합니다
- `APIManager`
- `TokenManager`

## 📝 To-do

- [x] `APIManager` (서버에 API 요청 시 사용합니다) 추가 수정 작업
    - 서버의 API JSON Response를 받을 `struct`를 설계 및 구현 (7개)
        - [x] `struct APIResponse`
        - [x] `struct Response`
        - [x] `struct ErrorResponse`
        - [x] `struct BadgeResponse`
        - [x] `struct Ranking`
        - [x] `struct BadgeListResponse`
        - [x] `struct BoolResponse`
    - **POST API** 구현 (7개)
        - [x] `fetchDataPOST` 함수 구현
        - [x] `/api/adventures`
        - [x] `/api/attendances`
        - [x] `/api/reissue`
        - [x] `/api/emails`
        - [x] `/api/badges/dream-of-duck`
        - [x] `/api/users/register`
        - [x] `/api/users/logout`
    - **GET API** 구현 (11개)
        - [x] `fetchDataGET` 함수 구현
        - [x] `/api/attendances`
        - [x] `/api/emails`
        - [x] `/api/badges`
        - [x] `/api/landmarks`
        - [x] `/api/landmarks/{ID}/highest`
        - [x] `/api/scores/rank`
        - [x] `/api/scores/rank/{ID}`
        - [x] `/api/users`
        - [x] `/api/users/notification`
        - [x] `/api/users/game-score`
        - [x] `/api/users/availability`
- [x] `TokenManager` (유저의 Token을 저장하고, 발급하고, 관리합니다)
    - [x] `UserDefaults`를 사용하여 앱 내부 DB에 토큰 및 정보 저장
