### ISSUE TITLE
[Feat] 다국어 지원 기능 구현

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#134]
## 🛠 Issue
다국어 지원을 위해 StringLiterals를 Localizable String File 구조로 수정합니다
- 영어 및 한국어

## 📝 To-do
- [x] 다국어 지원 세팅
- [x] 기타 파일들 수정
- [x] 한국어 세팅
- [ ] 영어 번역 추가
- [ ] 중국어 번역 추가

**Comment by leehe228** [comment]
기획팀에서 데이터 받으면 작업 예정!!!!
