### ISSUE TITLE
[Feat] Google Analytics 연동

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#147]
## 🛠 Issue
(출시 전) Google Analytics를 연동합니다

## 📝 To-do

- [x] FireBaseAnalytics 패키지 설정 
- [x] google analytics 연동
- [x] GAMAnager 생성 및 연동
