### ISSUE TITLE
[Feat] LoginView API 연결 및 뷰 내 로직 연결

### ISSUE THREAD

**Issue by Guryss** [playkuround/playkuround-iOS#19]
## 🛠 Issue

- LoginView API 연결 및 해당 뷰 내의 로직을 연결합니다.
- 3/21 회의에서 있었던 피드백을 반영합니다.

## 📝 To-do

- [X] LoginView API 연결
- [X] LoginView 로직 적용
- [X] `isPresented` 로 네이밍 수정
