### ISSUE TITLE
[Feat] RootView 구현 및 로그인 및 회원가입 flow 구현

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#20]
## 🛠 Issue
- 앱의 RootView를 설계하고 구현합니다.
- 로그인, 회원가입 로직에 따라 flow를 구현합니다
- 네트워크 검사, 토큰 검사 및 재발급 등 백그라운드 기능을 구현합니다

## 📝 To-do
- [x] View Flow 아키텍처 설계 및 구현
- [x] NetworkManager 연결
- [x] 앱 부팅 시 절차
    - [x] 토큰 검사 및 재발급
- [x] RootView 상에서 MainView LoginView RegisterView Flow 연결 및 구현
- [x] 위치 권한 거부 시 요청 뷰 `RequestPermissionView` UI 구현 및 연결

**테스트**
- [x] 네트워크 오류
- [x] 메인 - 로그인 - 이메일 인증 - 회원가입 - 홈 (미회원)
- [x] 메인 - 로그인 - 이메일 인증 - 홈 (토큰 만료)
- [x] 메인 - 홈 (토큰 유효)
