### ISSUE TITLE
[Feat] 심사용 예외 처리 및 릴리즈 준비 작업

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#202]
## 🛠 Issue
릴리즈용 심사 계정 예외 처리 및 릴리즈 준비 작업을 합니다
- 심사 예외 처리
- 배포 서버 설정

## 📝 To-do
- [x] 심사용 계정 개발 서버 처리
- [x] 심사용 계정 게임 플레이 예외처리
- [x] 배포 서버 설정
- [ ] 개발 서버 도메인 고정
- [x] 토스트 메시지 처리
- [x] 기타 테스트 및 디버깅
