### ISSUE TITLE
[Fix] QA 우선 기능적 수정사항 1차 반영

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#210]
## 🛠 Issue
- 토스트 메시지
- 회원가입 시 약관 동의한 경우에만 넘어가도록
- 홈 화면 랭킹 업데이트 반영
- notification 확인 (새 뱃지)
- 정복 랭킹 하단 토탈 점수 뜸
- 게임 중 홈 나갔다 들어오는 경우 초기화됨

## 📝 To-do
- [x] 토스트 메시지
- [x] 회원가입 시 약관 동의한 경우에만 넘어가도록
- [x] 홈 화면 랭킹 업데이트 반영
- [x] notification 확인 (새 뱃지)
- [x] 정복 랭킹 하단 토탈 점수 뜸
- [x] 게임 중 홈 나갔다 들어오는 경우 초기화됨
