### ISSUE TITLE
[Fix] QA 우선 디자인 수정사항 1차 반영

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#211]
## 🛠 Issue
- 랜드마크 건물 설명 수정
    - 제목 볼드 처리 및 좌측 정렬
- 랭킹 0위면 - 표시
- 마이페이지 "위" → "등"
- 랭킹 기준, 랭킹 점수 생략 처리 텍스트 수정
- "뱃지" → "배지"
- 로딩 다이얼로그 흰색으로 통일
- 지도 span, bound 처리

## 📝 To-do

- [x] 랜드마크 건물 설명 수정
    - 제목 볼드 처리 및 좌측 정렬
- [x] 랭킹 0위면 - 표시
- [x] 마이페이지 "위" → "등"
- [x] 랭킹 기준, 랭킹 점수 생략 처리 텍스트 수정
- [x] "뱃지" → "배지"
- [x] 로딩 다이얼로그 흰색으로 통일
