### ISSUE TITLE
[Fix] QA 10초를 맞춰봐, 덕쿠를 잡아라 게임 수정사항 반영

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#214]
## 🛠 Issue
- 10초를 맞춰봐 게임 사운드 변경
- 10초를 맞춰봐 점수 로직 수정 (v1.6)
- 덕쿠를 잡아라 로직 수정

## 📝 To-do
- [x] 10초를 맞춰봐 게임 사운드 변경
- [x] 10초를 맞춰봐 점수 로직 수정 (v1.6)
- [ ] 덕쿠를 잡아라 로직 수정

**Comment by leehe228** [comment]
오늘 새벽 내로 작업 완료하겠습니다~~
