### ISSUE TITLE
[Fix] QA 우선 기능적 수정사항 2차 반영

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#215]
## 🛠 Issue
- 랜드마크 건물 설명에 산학협동관 고정 나옴
- 마이페이지 등수 텍스트 "등" → "위" 수정
- 문을 점열해 카운트다운 추가
- 전체랭킹뷰 수정사항 반영
    - 닉네임 길어지는 경우 줄바꿈, 좌측 정렬
    - 제목 "랭킹"으로 수정
- 탐험 뷰 룰렛에서 게임 이름이 다 안나오는 경우
- 개인 알람 구현
- 문을 점령해 게임 오류 수정
    - 카운트다운 추가
    - 게임 종료 후 타이머 멈추도록
    - 점수가 여러 번 업로드되는 오류
    - 점수가 0점으로 올라가는 오류

## 📝 To-do
- [x] 랜드마크 건물 설명에 산학협동관 고정 나옴
- [x] 마이페이지 등수 텍스트 "등" → "위" 수정
- [x] 문을 점열해 카운트다운 추가
- [x] 전체랭킹뷰 수정사항 반영
    - 닉네임 길어지는 경우 줄바꿈, 좌측 정렬
    - 제목 "랭킹"으로 수정
- [x] 탐험 뷰 룰렛에서 게임 이름이 다 안나오는 경우
- [x] 개인 알람 구현
- [x] 문을 점령해 게임 오류 수정
