### ISSUE TITLE
[Fix] 수강신청 ALL 클릭 QA 반영

### ISSUE THREAD

**Issue by Guryss** [playkuround/playkuround-iOS#223]
## 🛠 Issue
- 수강신청 ALL 클릭 QA 내용 반영합니다. 

## 📝 To-do
- [x] 타이핑하면 자동으로 없어짐 → 엔터를 눌러야만 없어지도록 변경
- [x] 홈 화면 갔다 오면 과목 명이 사라져있음
- [x] 과목 명이 처음 낙하하는 위치가 ‘SCORE’ 와 목숨 아래에서 부터 
    → 호은: 일감호살아남기 보면 뷰 범위를 제한하고 넘는 것들 hidden 처리하면 될듯!
- [x] 글씨체 크기 수정 및 속도 수정
    - 글씨체 피그마와 크기가 다른 것 같음 너무 작음 (Android와 함께 수정) → 글씨 조금 더 키우면 될듯
    - 속도가 너무 빠름 (Android와 함께 수정)
- [x] 텍스트가 없을 때 플레이스홀더 뜨도록 수정
