### ISSUE TITLE
[Fix] 덕큐피트 QA 반영

### ISSUE THREAD

**Issue by Guryss** [playkuround/playkuround-iOS#224]
## 🛠 Issue
- 덕큐피트 게임 QA를 반영합니다. 

## 📝 To-do

- [x] BAD 시 덕쿠가 초기화
- [x] 홈 화면 갔다 오면 게임 초기화 
- [x] 게임 자체가 버벅임
