### ISSUE TITLE
[Fix] QA 우선 기능적 수정사항 3차 반영

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#245]
## 🛠 Issue
3차 QA 반영
- 다국어 일부 수정
- 텍스트 수정: 계정 삭제 → 탈퇴하기 및 메시지
- 약관 전체동의 누르면 전체 해제되도록
- 단과대 및 학과 선텍 메뉴 동시에 뜨지 않도록
- 회원가입 닉네임 뷰 수정
    - 닉네임 `onChange`마다 닉네임 validation 검사
    - 닉네임 중복 시 따로 중복이라고 띄워주지는 않음
- 일감호에서 살아남기 수정 
    - 게임 시간 60 → 120초 수정
    - Entity 생성 각도 수정
    - Entity 이동 속도 수정
    - 덕쿠 움직일 때 관성 추가
- 문을 점령해 타이머 수정
    - 타이머 속도가 약 2~3배로 감소됨 → 15초로 수정
- 건쏠지식 점수 수정
    - 점수 수정 (v1.5)
    - 기존에 점수가 2중으로 오르게 되어있어 수정
- 책 뒤집기
    - 여러 카드가 동시에 뒤집히는 문제
- 출석 뷰 날짜 수정 (요일 관계 없이 최근 30일)
- 게임 중단 시 "게임 점수가 반영되지 않았습니다" 토스트 메시지
- 수강신청ALL클릭 점수 로직 수정
    - 글자 수 4 이하: 2점, 8 이하: 4점, 나머지 6점
- 공지사항 버튼 누를 때마다 공지 받아오도록 수정

## 📝 To-do
- [x] 다국어 일부 수정
- [x] 텍스트 수정: 계정 삭제 → 탈퇴하기 및 메시지
- [x] 약관 전체동의 누르면 전체 해제되도록
- [x] 단과대 및 학과 선텍 메뉴 동시에 뜨지 않도록 
- [x] 회원가입 닉네임 뷰 수정 
    - 닉네임 `onChange`마다 닉네임 validation 검사
    - 닉네임 중복 시 따로 중복이라고 띄워주지는 않음
- [x] 일감호에서 살아남기 수정 
    - [x] 게임 시간 60 → 120초 수정
    - [x] Entity 생성 각도 수정 
    - [x] Entity 이동 속도 수정 
    - [x] 덕쿠 움직일 때 관성 추가
- [x] 문을 점령해 타이머 수정
    - 타이머 속도가 약 2~3배로 감소됨 → 15초로 수정
- [x] 건쏠지식 점수 수정 
    - 점수 수정 (v1.5)
    - 기존에 점수가 2중으로 오르게 되어있어 수정
- [x] 책 뒤집기
    - 여러 카드가 동시에 뒤집히는 문제
- [x] 출석 뷰 날짜 수정 (요일 관계 없이 최근 30일)
- [x] 게임 중단 시 "게임 점수가 반영되지 않았습니다" 토스트 메시지 
- [x] 수강신청ALL클릭 점수 로직 수정
    - 글자 수 4 이하: 2점, 8 이하: 4점, 나머지 6점
- [x] 공지사항 버튼 누를 때마다 공지 받아오도록 수정
