### ISSUE TITLE
[Fix] QA 수정사항 4차 반영

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#250]
## 🛠 Issue
QA 수정사항 4차 반영
- 토스트 메시지 배경 클릭 시 닫히도록 처리
- 정복랭킹 워딩 수정 을 → 을/를
- 마이페이지 Navigation바 z 조정
- 마이페이지 패딩 조정

## 📝 To-do

- [ ] 토스트 메시지 배경 클릭 시 닫히도록 처리
- [ ] 정복랭킹 워딩 수정 을 → 을/를
- [ ] 마이페이지 Navigation바 z 조정
- [ ] 마이페이지 패딩 조정
