### ISSUE TITLE
[Fix] QA 수정사항 5차 반영

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#254]
## 🛠 Issue
QA 수정사항 5차 반영
- 덕큐피트 조정
    - 덕큐피트 간격 조정 (perfect 0 ~ 8 → -4 ~ 4, good 8 ~ 16 → -8 ~ 8)
    - 덕큐피트 점수 조정 (perfect 3 → 5점, good 1 → 2점)
- 일감호 살아남기 
    - life 안깎임 수정 (디버깅)
    - 일감호 살아남기 자이로스코프 누적 문제 (기울인 채로 시작하면 안움직임)
- 덕쿠를 잡아라 게임 이름 텍스트 수정
- 홈뷰에서 공지 버튼 new! 제거 (안드로이드와 맞춤)
- 덕쿠를 잡아라 덕쿠 생성 로직 수정

## 📝 To-do

- [x] 덕큐피트 조정
    - 덕큐피트 간격 조정 (perfect 0 ~ 8 → -4 ~ 4, good 8 ~ 16 → -8 ~ 8)
    - 덕큐피트 점수 조정 (perfect 3 → 5점, good 1 → 2점)
- [x] 일감호 살아남기 
    - life 안깎임 수정 (디버깅)
    - 일감호 살아남기 자이로스코프 누적 문제 (기울인 채로 시작하면 안움직임)
- [x] 덕쿠를 잡아라 게임 이름 텍스트 수정
- [x] 홈뷰에서 공지 버튼 new! 제거 (안드로이드와 맞춤)
- [x] 덕쿠를 잡아라 덕쿠 생성 로직 수정
