### ISSUE TITLE
[Fix] 1차 수정사항 패치 

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#261]
## 🛠 Issue
1차 수정사항
- 공지사항 제목 중앙 정렬
- 배경음악 저작권 정보 추가
- 게임 (하단 바 숨겨지도록)

## 📝 To-do
- [ ] 공지사항 제목 중앙 정렬
- [ ] 배경음악 저작권 정보 추가
- [ ] 게임 (하단 바 숨겨지도록)
