### ISSUE TITLE
[Design] 일시정지뷰, 카운트다운뷰, 10초를 맞춰봐 게임 UI 구현

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#46]
## 🛠 Issue
10초를 맞춰봐 게임 UI를 구현합니다
게임에서 사용되는 일시정지뷰, 카운트다운뷰 UI를 구현합니다

## 📝 To-do

- [x] 10초를 맞춰봐 게임 UI 구현
- [x] 일시정지뷰 UI 구현
- [x] 카운트다운뷰 UI 구현
