### ISSUE TITLE
[Feat] GameViewModel 개발

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#49]
## 🛠 Issue
게임 시 MVVM GameView를 위한 Abstract Class인 GameViewModel 클래스를 구현합니다

## 📝 To-do

- [x] GameViewModel 구현
    - [x] 게임에서 사용되는 타이머 구현
    - [x] 게임 종료 시 점수 업데이트 기능 구현 (API 연결)
    - [x] 게임 시작 전 카운트다운 기능 추가
    - [x] 일시정지, 계속하기, 홈으로 기능 추가
- [x] 타이머 관련하여 알 수 없는 오류 발생 (수정 필요)
- [x] Game 관련 공통 파일들 Games/Common 폴더 내로 옮기기
