### ISSUE TITLE
[Feat] 수강신청 ALL 클릭 게임 로직 구현

### ISSUE THREAD

**Issue by Guryss** [playkuround/playkuround-iOS#84]
## 🛠 Issue
- 수강신청 All 클릭 게임 로직을 구현합니다. 

## 📝 To-do

- [x] 점수 계산 로직
- [x] 생명 없어지기
- [x] 시간 지날수록 속도 증가 
- [x] 텍스트 x, y offset 수정
- [x] pause, finish 되었을 때 키보드 내림
- [x] 키보드 + 입력창 높이 인식 -> 글자 사라지기
