### ISSUE TITLE
[Setting] Badge, Major, UserNotification, ScoreType 구조화 작업

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#9]
## 🛠 Issue
앱 내에서 사용되는 아래 리스트를 `enum` 타입으로 구조화합니다
- Badge (뱃지)
- Major (학과) 및 College (단과대)
- UserNotification (유저 알림)
- ScoreType (점수 종류)
- ~Landmark (랜드마크)~

## 📝 To-do

- [x] `Data` 폴더 생성
- [x] Badge `enum` 구조화
- [x] Major 및 College `struct` 구조화
- [x] UserNotification `enum` 구조화
- [x] ScoreType `enum` 구조화
- ~Landmark `enum` 구조화~
→ Landmark는 백엔드 서버에서 처리하므로 구조화가 필요없다고 판단하여 제외했습니다
