### ISSUE TITLE
[Feat] APIManager 서버 Healthy 체크 및 Timeout 관련 기능 추가 개발

### ISSUE THREAD

**Issue by leehe228** [playkuround/playkuround-iOS#93]
## 🛠 Issue
APIManager에 필요한 추가 기능을 개발합니다
- Server Healthy Check (서버가 정상적으로 응답하는지 체크)
- Timeout (서버가 몇 초 이내 응답 없는 경우 오류 반환)
- Refactoring (성능 개선 및 최적화)
- Response Parsing (response에 뱃지 등 데이터가 함께 반환되는 경우 처리

## 📝 To-do

- [ ] Server Healthy Check
- [ ] Timeout 
- [ ] 위 기능에 따른 예외 처리
- [ ] Refactoring

추가 필요 기능
- [ ] 출석 실패와 같이 서버에서 실패를 내려주는 경우 안내 메시지
- [ ] 뱃지 받았을 때
